### ISSUE TITLE
Información sobre SpringFramework

### ISSUE THREAD

**Issue by DatFerPa** [Arquisoft/participants1a#1]
Buscar información sobre SpringFramework y adjuntar aquí enlaces:

**Comment by lauramenpe** [comment]
Spring framework:
- https://spring.io/guides/gs/rest-service/
- http://www.tutorialspoint.com/spring/
- https://docs.spring.io/spring/docs/current/spring-framework-reference/html/jdbc.html
- http://www.journaldev.com/8718/spring-4-security-mvc-login-logout-example
- https://www.youtube.com/watch?v=MQlcLrCrzNc
JDBC, Oracle:
- https://springframework.guru/configuring-spring-boot-for-oracle/
- http://sivalabs.in/2016/03/springboot-working-with-jdbctemplate/

**Comment by DatFerPa** [comment]
Enlaces:

- http://www.arquitecturajava.com/que-es-spring-boot/
- https://www.paradigmadigital.com/dev/microservicios-spring-boot-14-introduccion/
- http://ictblog.luisalbertogh.net/?p=424
- http://acodigo.blogspot.com.es/2014/11/spring-boot-introduccion.html

- PDF con ejemplos: https://www.google.es/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=0ahUKEwitqsPvyvHRAhWi4IMKHUnfDw4QFggiMAE&url=http%3A%2F%2Fsamples.leanpub.com%2Fspringboot-learn-by-example-sample.pdf&usg=AFQjCNGlNOfJte-8I_ddleegKiWj0S309Q&sig2=FD4L8mXzNB3Tnnl-USQFUA&bvm=bv.146073913,d.cGc

Adjunto el repositorio de proyectos de Spring: https://github.com/spring-projects y el de Spring Boot: https://github.com/spring-projects/spring-boot/tree/master/spring-boot-starters

**Comment by martinp95** [comment]
No tiene sonido pero esta bastante completo 
-https://www.youtube.com/watch?v=sDRbeUAlj2U

**Comment by dave36** [comment]
Aquí está toda la documentación del framework. Está bien explicada con ejemplos y demás, aunque está en ingles:
http://docs.spring.io/spring/docs/3.1.0.M2/spring-framework-reference/html/index.html

Se explica el framework Spring para Web, como tener una base de datos para la aplicación, como acceder a datos mediante JPA y la integración de la apliación mediante tests. Está muy bien estructurado y completo. El entorno que utiliza es eclipse y también se explican los primeros pasos en este framework:
http://www.uv.es/grimo/teaching/SpringMVCv4PasoAPaso/index.html
