### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by lauramenpe** [Arquisoft/participants1a#4]
Servicio web muy simple que toma como parámetros codificados en una llamada POST el email del usuario y la clave, y devuelva información sobre los datos en formato JSON que figuran sobre el ciudadano en el sistema en caso correcto o informe del error en caso incorrecto.

**Comment by DatFerPa** [comment]
Revisar método de verificación de email

**Comment by DatFerPa** [comment]
Limpiar código según codacy
